name: Fittech
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  dio: ^5.4.0
  app_links: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logoo.png
    - assets/images/logo.png
    - assets/images/icon_logo.png
    - assets/images/background_image.png
    - assets/images/carousel1.png
    - assets/images/carousel2.png
    - assets/images/carousel3.png
    - assets/images/carousel4.png
    - assets/images/splash_bg.png
    - assets/images/signup_bg.png
    - assets/images/tr_success_bg.png