version: '3.8'

networks:
  fittech-network:
    driver: bridge

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fittech-network

  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - fittech-network

  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - fittech-network

  subscription-db:
    image: mysql:8
    container_name: subscription-db
    environment:
      MYSQL_DATABASE: subscription_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    networks:
      - fittech-network

  booking-db:
    image: mysql:8
    container_name: booking-db
    environment:
      MYSQL_DATABASE: booking_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    networks:
      - fittech-network

  activity-db:
    image: mysql:8
    container_name: activity-db
    environment:
      MYSQL_DATABASE: activity_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3311:3306"
    networks:
      - fittech-network